"""Filesystem storage backend."""

from __future__ import annotations

import logging
import re
import shutil
from pathlib import Path
from typing import IO

from app.core.errors import StorageError
from app.storage.base import StorageBackend

logger = logging.getLogger(__name__)

# Keys are generated by the application, never by a user. This pattern is the
# belt-and-braces check that nothing resembling a path traversal can get through.
_SAFE_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$")


class LocalFileStorage(StorageBackend):
    """Stores objects as files beneath a single root directory."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        """Map a key to a path, refusing anything that escapes the root."""
        if not _SAFE_KEY.match(key) or ".." in key:
            raise StorageError(f"Refusing to use an unsafe storage key: {key!r}")

        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root.resolve()):
            raise StorageError("Refusing to write outside the storage root.")
        return path

    def save(self, key: str, stream: IO[bytes]) -> int:
        path = self._resolve(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with path.open("wb") as destination:
                shutil.copyfileobj(stream, destination, length=1024 * 1024)
        except OSError as exc:
            logger.exception("Failed to store %s", key)
            raise StorageError("The file could not be saved.") from exc
        return path.stat().st_size

    def open(self, key: str) -> IO[bytes]:
        path = self._resolve(key)
        try:
            return path.open("rb")
        except OSError as exc:
            raise StorageError("The stored file could not be read.") from exc

    def delete(self, key: str) -> None:
        try:
            self._resolve(key).unlink(missing_ok=True)
        except OSError:
            # A file we cannot delete is a housekeeping problem, not a request
            # failure — the database row is what the user actually sees.
            logger.warning("Could not delete stored object %s", key, exc_info=True)

    def exists(self, key: str) -> bool:
        return self._resolve(key).is_file()

    def local_path(self, key: str) -> Path | None:
        return self._resolve(key)
